# -*- mode: ruby -*-
# vi: set ft=ruby :

unless File.exist? "/etc/vbox/networks.conf"
    # See https://www.virtualbox.org/manual/ch06.html#network_hostonly
   puts "Adding network configuration for VirtualBox."
   puts "You will need to enter your root password..."
   system("sudo bash vbox-network.sh")
 end
 
 Vagrant.configure("2") do |config|
   config.vm.box = "bento/ubuntu-22.04"
 
   config.vm.network "private_network", type: "dhcp"
 
   config.vm.provision "file", source: "./", destination: "./"
 
   config.vm.define "itu-minitwit", primary: true do |server|
     server.vm.network "private_network", ip: "192.168.20.2"
     server.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
     end
     server.vm.hostname = "itu-minitwit"
     server.vm.provision "shell", privileged: true, inline: <<-SHELL
        cd "Chirp Project"
       ./docker-cli.sh

       docker build -t vagrant-minitwit:latest .
       docker run -d -p 8080:8080 --name minitwit vagrant-minitwit:latest
     SHELL
   end
 end